import React from 'react';
import Head from 'next/head';

const CARDS = [
  {
    id: 1,
    img: 'https://picsum.photos/1000',
    title: 'Card 1',
    desc: 'Sample Text 1',
    author: 'Author 1',
    full: false,
  },
  {
    id: 2,
    img: 'https://picsum.photos/1300',
    title: 'Card 2',
    desc: 'Sample Text 2',
    author: 'Author 2',
    full: true,
  },
  {
    id: 3,
    img: 'https://picsum.photos/1100',
    title: 'Card 3',
    desc: 'Sample Text 3',
    author: 'Author 3',
    full: true,
  },
  {
    id: 4,
    img: 'https://picsum.photos/1500',
    title: 'Card 4',
    desc: 'Sample Text 4',
    author: 'Author 4',
    full: false,
  },
];

function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/project-it-image.png" />
      </Head>

      <main className="p-3 mx-auto" style={{ maxWidth: '90rem' }}>
        <h1 className="display-4 fs-1">Home</h1>
      </main>
    </>
  );
}

export default Home;
