import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet" />
      </Head>

      <main className='p-3 mx-auto' style={{ maxWidth: '90rem' }}>
        <div
          id='hero'
          className='container d-flex flex-column align-items-center justify-content-center my-4'
        >
          <h4 className='display-4'>
            Welcome to <strong>Project It</strong>.
          </h4>
          <p className='fs-3 mb-5'>Get started by viewing public projects.</p>

          <Link href='/cards'>
            <button className='btn btn-lg btn-primary'>
              <strong>
                <i className='bi bi-collection text-white'></i> Projects
              </strong>
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}

export default Home;
